const touches = [...document.querySelectorAll('.button')]

const listkeycode = touches.map(touche=> touche.dataset.key)

const screen = document.querySelector('.screen-calculator')

document.addEventListener('keydown',(e) =>{
    const valeur = e.keyCode.toString();
    calculer (valeur);
    
} )

document.addEventListener('click',(e) =>{
    const valeur = e.target.dataset.key ;
     calculer (valeur)
}
)

const calculer = (valeur) =>{
    if (listkeycode.includes(valeur)) {
        console.log(listkeycode);
    }
    switch (valeur) {
        case '8':
            screen.textContent = '';
            break;

        case '13':
            const calcul = eval(screen.textContent);
            screen.textContent = calcul
            break;

        default:
            const indexKeycode = listkeycode.indexOf(valeur);
            const touch = touches[indexKeycode]
            screen.textContent += touch.innerHTML 
            break;
    }
}

window.addEventListener('error', (e) => {
    alert('une erreur est survenu dans votre calcul :'+ e.message)
})



